### ISSUE TITLE
Option to "disable sentence segmentation" needed

### ISSUE THREAD

**Issue by KoichiYasuoka** [TakeLab/spacy-udpipe#13]
I used "lzh" model, but its performance for sentence segmentation seems rather worse. So I tried to disable sentence segmentation:

```
import spacy_udpipe
class M(spacy_udpipe.UDPipeModel):
  def tokenize(self,text:str):
    t=self.model.newTokenizer(self.model.TOKENIZER_PRESEGMENTED)
    return self._read(text=text,input_format=t)
m=M("lzh")
lzh=spacy_udpipe.UDPipeLanguage(m,m._meta)
doc=lzh("不入虎穴不得虎子")
```

This quick hack works well, and I think we need an option for `spacy_udpipe.load` to disable sentence segmentation. How do you think, @asajatovic ?

**Comment by asajatovic** [comment]
@KoichiYasuoka Based on the results from the official [UDPipe benchmarks](https://ufal.mff.cuni.cz/udpipe/models), the `Classical Chinese-Kyoto` model (the `lzh` model) has improved sentence segmentation performance, although it is still subpar. The situation is similar for other antique languages.

Regarding your proposed solution - could a simple rule-based [`Sentencizer`](https://spacy.io/usage/linguistic-features#sbd-component) work for sentence segmentation of Classical Chinese? As `TOKENIZER_PRESEGMENTED` does not determine sentence boundaries, a custom `Sentencizer` could be added to `Language.pipeline`.

As this is a language-specific (performance) issue, I need more time to think about adding a fix to the release version. I do not think it is a good idea to have (m)any `if-else` cases for each specific language as the main idea behind `spacy-udpipe` is to be as language-agnostic as possible.
The best way to solve similar language-specific issues would be upstream - meaning in [spaCy language subclasses](https://spacy.io/usage/adding-languages#language-subclass) or with improved [UDPipe models](https://ufal.mff.cuni.cz/udpipe/models#universal_dependencies_25_models), i.e. larger training corpora.

I would like to encourage you to try the `Sentencizer` approach and perhaps even open a pull request when you are happy with the solution. Given that I do not speak a word of Chinese, I could only help you with Python code (and gladly would).
In the meantime, I will take a closer look at the performance of the latest UDPipe models (focusing on sentence segmentation) and think more about incorporating a fix in the release version.

**Comment by asajatovic** [comment]
@KoichiYasuoka after some consideration, I think it could work as there are a few ancient languages that could benefit from pre-segmented text input.
What concerns me is how the end-user will be able to provide pre-segmented text required for this.  I'd like to know what you think about this?
Unfortunately, I am too busy to work on this, so I'd like to encourage you to do it (if you are up for it)! :smile:

**Comment by asajatovic** [comment]
@KoichiYasuoka, I initially thought it would be much harder to enable than it was in #19.
It works now!  :sweat_smile:
