### ISSUE TITLE
Noun chunks in Czech language

### ISSUE THREAD

**Issue by xricht29** [TakeLab/spacy-udpipe#28]
Because the Czech isn't supported in Spacy, I use UDPipe model czech-pdt-ud-2.5-191206.udpipe with Spacy-udpipe. The problem is that iterating through the noun chunks doesn't work for czech.
Is there any way to manually specify lang/cs/syntax_iterators.py in Spacy, or any other way how to deal with it? Thanks for any advice.

**Comment by asajatovic** [comment]
Please check out spaCy documentation on [syntax iterators](https://spacy.io/usage/adding-languages#syntax-iterators). (It is also addressed in the [Notes section](https://github.com/TakeLab/spacy-udpipe#notes))
