### ISSUE TITLE
Support spacy v3 ?

### ISSUE THREAD

**Issue by wayne315315** [TakeLab/spacy-udpipe#31]
As titled, will this awesome project support spacy >= 3.0.0 ?
Now, it seems only work with spacy <= 2.3.5

**Comment by asajatovic** [comment]
Thanks for asking, I appreciate your interest. I'm glad to say this is a work in progress, so stay tuned! :grin:

**Comment by KoichiYasuoka** [comment]
Hi @wayne315315, I've just written quick enhancement for spaCy v3.0. Please drop by https://github.com/KoichiYasuoka/spacy-udpipe .

**Comment by asajatovic** [comment]
enabled in #35
